name: itunes_assignment
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.7
  http: ^1.1.0
  flutter_riverpod: ^2.4.10
  cached_network_image: ^3.3.1
  video_player: ^2.8.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:

  color: "#6A6969"

  image: assets/app_logo.png

  android_12:

    image: assets/app_logo.png

    # Splash screen background color.
    color: "#6A6969"

